name: Demo Test Run

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout (including submodules)
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'

    - name: Run REST API tests
      run: |
        ./gradlew runStories -Pvividus.configuration.suites=rest_api \
                             -Pvividus.allure.history-directory=output/history/rest-api-tests

    - name: Publish REST API tests report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: REST API tests report
        path: output/reports/allure
